# Covered here

* [A condensed NumPy manual: useful chapters in *NumPy Reference*](#A-condensed-NumPy-manual:-useful-chapters-in-NumPy-Reference)
* [The NumPy array (`ndarray`)](The-NumPy-array-(ndarray)
* [Axes](#Axes)
* [Shape manipulation](#Shape-manipulation)
* [Indexing & slicing](Indexing-&-slicing)
* [Broadcasting](#Broadcasting)
* [Vectorization](#Vectorization)

# Resources & references

* [NumPy basics](https://docs.scipy.org/doc/numpy-dev/user/basics.html)
* [NumPy Reference](https://docs.scipy.org/doc/numpy-dev/reference/index.html#numpy-reference)
* [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)
* [Complete NumPy manual](https://docs.scipy.org/doc/numpy/contents.html) (table of contents)
* [NumPy Tutorial](http://www.python-course.eu/numpy.php), from python-course.eu

# A condensed NumPy manual: useful chapters in _NumPy Reference_

This list is not inclusive--it includes selected chapters.  See full [here](https://docs.scipy.org/doc/numpy/contents.html).

* [Array objects](https://docs.scipy.org/doc/numpy/reference/arrays.html)
 * [The N-dimensional array](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html)
 * [Data type objects](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html)
 * [Indexing](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)
 * [Iterating over arrays](https://docs.scipy.org/doc/numpy/reference/arrays.nditer.html)
 * [Masked arrays](https://docs.scipy.org/doc/numpy/reference/maskedarray.html)
 * [Datetimes and timedeltas](https://docs.scipy.org/doc/numpy/reference/arrays.datetime.html)
* [Universal functions (`ufunc`)](https://docs.scipy.org/doc/numpy/reference/ufuncs.html)
* [Routines](https://docs.scipy.org/doc/numpy/reference/routines.html)
 * [Array creation routines](https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html)
 * [Array manipulation routines](https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html)
   * Included here: `reshape`, `ravel`, `flatten`, `swapaxes`, `squeeze`, `stack`, `block` and others
 * [Financial functions](https://docs.scipy.org/doc/numpy/reference/routines.financial.html)
 * [Functional programming](https://docs.scipy.org/doc/numpy/reference/routines.functional.html) 
   * Included here: `apply_along_axis`, `apply_over_axes`, `vectorize`
 * [Indexing routines](https://docs.scipy.org/doc/numpy/reference/routines.indexing.html)
 * [Input & output](https://docs.scipy.org/doc/numpy/reference/routines.io.html)
 * [Linear algebra](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)
 * [Logic functions](https://docs.scipy.org/doc/numpy/reference/routines.logic.html)
 * [Masked array operations](https://docs.scipy.org/doc/numpy/reference/routines.ma.html) [conflict w/ earlier section?]
 * [Mathematical functions](https://docs.scipy.org/doc/numpy/reference/routines.math.html)
 * [Random sampling](https://docs.scipy.org/doc/numpy/reference/routines.random.html) (`numpy.random`)
 * [Set routines](https://docs.scipy.org/doc/numpy/reference/routines.set.html)
 * [Sorting, searching, and counting](https://docs.scipy.org/doc/numpy/reference/routines.sort.html)
 * [Statistics](https://docs.scipy.org/doc/numpy/reference/routines.statistics.html)
   * Note: you want `np.corrcoef`, not `np.correlate`.  The latter returns a cross-correlation as used in [signal processing](https://en.wikipedia.org/wiki/Cross-correlation).

# The NumPy array (`ndarray`)

NumPy, short for Numerical Python, is the fundamental package required for high-performance scientific computing and data anlysis.  It is the foundation on which nearly all the higher-level Python tools are built.  The essential problem that NumPy solves is fast array processing. NumPy’s main object is the homogeneous multidimensional array.  **NumPy gives Python an array object that is much more efficient and better suited for mathematical calculation than a standard Python list.**  Arrays generally structure objects in rows and columns.  The simplest case is a one-dimensional array that represents, mathematically speaking, a vector of numbers.  Arrays could also be _i x j_, _i x j x k_, etc.

Arithmetic operators on arrays apply _elementwise_.  This is a critically important feature, and it allows for mathematical operations on whole blocks of data using operations that are usually performed on scalars.  This is closely related to the concept of [_vectorization_](https://en.wikipedia.org/wiki/Array_programming) (see also the separate section below), which refers to expressing batch operations on data without writing any for loops.

Resources: 
* [The N-dimensional array (ndarray)](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html)
* [array creation routines](https://docs.scipy.org/doc/numpy-dev/reference/routines.array-creation.html#routines-array-creation)
* [Array methods](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html#array-methods)

In NumPy dimensions are called axes. The number of axes is *rank*.  Important attributes of the `ndarray` (`numpy.array`):

In [1]:
a = np.arange(15).reshape(3, 5)

In [2]:
a.shape

(3, 5)

In [3]:
a.ndim

2

In [4]:
a.dtype.name

'int64'

In [5]:
a.size

15

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.  The function `zeros` creates an array full of zeros, the function `ones` creates an array full of ones, and the function `empty` creates an array whose initial content is random and depends on the state of the memory.

In [6]:
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [7]:
np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [8]:
np.empty( (2,3) )                                 # uninitialized, output may vary

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [9]:
a < 7

array([[ True,  True,  True,  True,  True],
       [ True,  True, False, False, False],
       [False, False, False, False, False]], dtype=bool)

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the dot function or method:

In [10]:
A = np.array( [[1,1], [0,1]] )

In [11]:
B = np.array( [[2,0], [3,4]] )

In [12]:
A * B # elementwise product

array([[2, 0],
       [0, 4]])

In [13]:
np.dot(A, B) # matrix product

array([[5, 4],
       [3, 4]])

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [14]:
a = np.random.random((2,3))

In [15]:
a.sum(), a.min(), a.max()

(1.8339991178666906, 0.0067425558614718772, 0.73249003465962192)

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array.
* `axis=0` --> compute for each column
* `axis=1` --> compute for each row

In [16]:
b = np.arange(12).reshape(3,4); b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
b.sum(axis=0)                            # sum of each column

array([12, 15, 18, 21])

In [18]:
b.min(axis=1)                            # min of each row

array([0, 4, 8])

NumPy provides familiar mathematical functions such as _sin_, _cos_, and _exp_. In NumPy, these are called “universal functions”(`ufunc`). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [19]:
B = np.arange(3)

In [20]:
np.exp(B)

array([ 1.    ,  2.7183,  7.3891])

In [21]:
C = np.array([2., -1., 4.])

In [22]:
np.add(B, C)

array([ 2.,  0.,  6.])

## Array creation

The `size` parameter of most functions can be a shape rather than scalar:

In [23]:
# alternative to np.random.randint(-10,10).reshape(5,7):
print(np.random.randint(-10,10,(5,7)))

[[ -9   2   5  -1   3   4  -8]
 [  7  -5  -2  -4  -1  -5   5]
 [ -5   7  -6   9  -4   6   4]
 [  0   0  -3  -5   1  -1   5]
 [ -2  -7  -7   6   6 -10  -3]]


# Axes

See also: [SO: What does axis in pandas mean?](https://stackoverflow.com/questions/22149584/what-does-axis-in-pandas-mean)

The terminology around axes in NumPy and pandas can be counterintuitive.  Frequnelty in pandas and NumPy parameter documentation you will see:

<center>`axis : {index (0), columns (1)}`</center>

However, the following example might seem to disagree at first glance:

In [24]:
arr = np.array([[1, 2],
                [3, 4]])

# df = pd.DataFrame(arr, columns=list('ab'))
# print(df)

In [25]:
arr.sum(axis=0)

array([4, 6])

In [26]:
arr.sum(axis=1)

array([3, 7])

The key to `axis` is that it specifies the axis _along which_ the function is called.  In other words, 
* `axis=0` applies the callable _along_ rows (it is _column-wise_) [you'll get a result for each column]
* `axis=1` applies the callable _along_ columns (it is _row-wise_) 

# Shape manipulation

In [27]:
def f(x,y):
    return 10*x+y

In [28]:
b = np.fromfunction(f,(5,4),dtype=int)

In [29]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [30]:
b.ravel()  # returns the array, flattened

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

Several arrays can be stacked together along different axes:

In [31]:
a = np.ones( (3, 4) )

In [32]:
np.vstack((a, b)) # note np.hstack((a, b)) would give ValueError here

array([[  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  0.,   1.,   2.,   3.],
       [ 10.,  11.,  12.,  13.],
       [ 20.,  21.,  22.,  23.],
       [ 30.,  31.,  32.,  33.],
       [ 40.,  41.,  42.,  43.]])

See also [numpy.column_stack](https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.column_stack.html#numpy.column_stack).

# Indexing & slicing

Array indexing refers to any use of the square brackets (`[]`) to index array values.  Assigning to and accessing the elements of an array is similar to other sequential data types of Python, i.e. lists and tuples.  The general syntax for a one-dimensional array `A` looks like this: `A[start:stop:step]`.  It is 0-based, and accepts negative indices for indexing from the end of the array.

There are three kinds of indexing available in NumPy:
1. Field access
2. Basic slicing
3. Advanced indexing

Which one occurs depends on `obj` when indexing an `ndarray` with `x[obj]`.  [Field access](https://docs.scipy.org/doc/numpy-1.12.0/reference/arrays.indexing.html#field-access) is not covered here because it applies to structured arrays.

See also: [indexing documentation](https://docs.scipy.org/doc/numpy-dev/user/basics.indexing.html).

## Basic slicing

* Extends Python's basic conept of slicing to _N_ dimensions
* Basic slicing occurs when `obj` is a one of:
 * A [slice](https://docs.python.org/dev/library/functions.html#slice) object (constructed by `start:stop:step` notation inside brackets)
 * An integer
 * A tuple of slice objects and integers
* **All arrays generated by basic slicing are always [views](https://docs.scipy.org/doc/numpy-1.12.0/glossary.html#term-view) of the original array**
* The basic slice syntax is `i:j:k` where `i` is the starting index, `j` is the stopping index, and `k` is the step ($k\neq0$)
 * `i` is inclusive; **`j` is exclusive**:

In [33]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[3] # 0-indexed; inculsive

3

In [34]:
x[1:3] # 3 is exclusive

array([1, 2])

Negative `i` and `j` are interpreted as `n + i` and `n + j` where **`n` is the number of elements in the corresponding dimension**:

In [35]:
len(x) # n

10

In [36]:
x[-2:10] # -i is interpreted as n + i = 10 + (-2) = 8

array([8, 9])

In [37]:
x[8:10] # a check on the above

array([8, 9])

Negative `k` makes stepping go towards smaller indices:

In [38]:
x[-3:3:-1] # -i is interp. as 7; slice is 7:3 (3 is still exclusive)
           # the k=-1 step is required here (would yield empty array otherwise)

array([7, 6, 5, 4])

Assume _n_ is the number of elements in the dimension being sliced. Then:
* If `i` is not given it defaults to 0 for _k > 0_ and _n - 1_ for _k < 0_ 
* If `j` is not given it defaults to _n_ for _k > 0_ and _-1_ for _k < 0_
* If `k` is not given it defaults to 1. 

Note that `::` is the same as `:` and means select all indices along this axis.

In [39]:
x[5:] # j is not given; defaults to len(x) = 10

array([5, 6, 7, 8, 9])

In [40]:
x[5:10] # a check of the above

array([5, 6, 7, 8, 9])

One more example...

In [41]:
x = np.arange(10,1,-1); x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [42]:
x[np.array([3, 3, 1, 8])] # The index array consisting of the values 3, 3, 1 and 8 correspondingly create 
                          # an array of length 4 (same as the index array) where each index is replaced by 
                          # the value the index array has in the array being indexed

array([7, 7, 9, 2])

# Advanced indexing

* Advanced indexing occurs when `obj` is a one of:
 * A non-tuple sequence object
 * An `ndarray`
 * A tuple with at least one sequence object or ndarray
* Advanced indexing always returns a copy of the data (contrast with basic slicing that returns a view)
* There are two types of advanced indexing: 
 1. Integer
 2. Boolean

## Integer array indexing

In [43]:
x = np.array([[1, 2], [3, 4], [5, 6]])
print(x)
print('ndim: %d' % x.ndim)

[[1 2]
 [3 4]
 [5 6]]
ndim: 2


While these slices may appear complixated, the still follow the format of [rows, columns].  Below,
* `[0, 1, 2]` is an index of rows to use, and
* `[0, 1, 0]` specifies the element (column) to choose for the corresponding row

In [44]:
x[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

In [45]:
x = np.arange(12).reshape((4, 3)); x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

From a 4x3 array the corner elements should be selected using advanced indexing. Thus all elements for which the column is one of `[0, 2]` and the row is one of `[0, 3]` need to be selected.

In [46]:
rows = np.array([[0, 0],
                 [3, 3]], dtype=np.intp)
columns = np.array([[0, 2],
                    [0, 2]], dtype=np.intp)
x[rows, columns]

array([[ 0,  2],
       [ 9, 11]])

This broadcasting can also be achieved using the function `ix_`:

In [47]:
rows = np.array([0, 3], dtype=np.intp)
columns = np.array([0, 2], dtype=np.intp)
x[np.ix_(rows, columns)]

array([[ 0,  2],
       [ 9, 11]])

More examples:

In [48]:
x[1:2, 1:3]

array([[4, 5]])

In [49]:
x[1:2, [1, 2]]

array([[4, 5]])

## Useful examples: multidimensional array indexing

There are two main ways to index a multidimensional array index: through a single CSV list, or chained lists.  The first method is greatly preferable due to speed and reliability.  (And the second, when used for chained assignment, is dangerous.)  Note that CSV-indexing is not possible for native lists or tuples.

In [50]:
A = np.array([ [3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8]])

In [51]:
A[0, 1] # CSV

8.6999999999999993

In [52]:
A[0][1] # chained lists
        # a new temporary array is created after the first index that is subsequently indexed by 1

8.6999999999999993

An extended multidimensional indexing example:

In [53]:
A = np.array([
    [11,12,13,14,15],
    [21,22,23,24,25],
    [31,32,33,34,35],
    [41,42,43,44,45],
    [51,52,53,54,55]])

In [54]:
A[:3,2:]

array([[13, 14, 15],
       [23, 24, 25],
       [33, 34, 35]])

![a1.png](imgs/a1.png)

In [55]:
A[3:,:]

array([[41, 42, 43, 44, 45],
       [51, 52, 53, 54, 55]])

![a2.png](imgs/a2.png)

In [56]:
A[:,4:]

array([[15],
       [25],
       [35],
       [45],
       [55]])

![a3.png](imgs/a3.png)

The following examples use the third parameter "step".

In [4]:
X = np.arange(28).reshape(4,7)

In [5]:
X[::2, ::3]

array([[ 0,  3,  6],
       [14, 17, 20]])

![x1.png](imgs/x1.png)

In [6]:
X[::, ::3]

array([[ 0,  3,  6],
       [ 7, 10, 13],
       [14, 17, 20],
       [21, 24, 27]])

![x2.png](imgs/x2.png)

One more example...

In [60]:
y = np.arange(35).reshape(5,7); y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [61]:
y[:, ::3]

array([[ 0,  3,  6],
       [ 7, 10, 13],
       [14, 17, 20],
       [21, 24, 27],
       [28, 31, 34]])

In [62]:
y[1:5:2]

array([[ 7,  8,  9, 10, 11, 12, 13],
       [21, 22, 23, 24, 25, 26, 27]])

In [63]:
y[1:5:2,::3] # before and after the comma refers to different axes!

array([[ 7, 10, 13],
       [21, 24, 27]])

As was seen in the section on indexing 1D arrays, arrays can be indexed by arrays of integers (of different shape).  This is referred to as an [index array](https://docs.scipy.org/doc/numpy-dev/user/basics.indexing.html#other-indexing-options).

In [64]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )      # a bidimensional array of indices

In [65]:
a[j]                                       # the same shape as j

IndexError: index 3 is out of bounds for axis 0 with size 3

In [66]:
a = np.arange(12).reshape(3,4)

In [67]:
i = np.array( [ [0,1], [1,2] ] ) # indices for the first dim of a

In [68]:
j = np.array( [ [2,1], [3,3] ] ) # indices for the second dim

In [69]:
a[i,j]

array([[ 2,  5],
       [ 7, 11]])

## Indexing with Boolean Arrays

The most natural way one can think of for boolean indexing is to use boolean arrays that have the same shape as the original array:

In [70]:
a = np.arange(12).reshape(3,4)

In [71]:
b = a > 4

In [72]:
b # b is a boolean with a's shape

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [73]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [74]:
x = np.array([[0, 1], [1, 1], [2, 2]]); x

array([[0, 1],
       [1, 1],
       [2, 2]])

In [75]:
rowsum = x.sum(-1); rowsum

array([1, 2, 4])

In [76]:
x[rowsum <= 2, :]

array([[0, 1],
       [1, 1]])

## Structural indexing tools

To facilitate easy matching of array shapes with expressions and in assignments, the `np.newaxis` object can be used within array indices to add new dimensions with a size of 1:

In [77]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [78]:
y.shape

(5, 7)

In [79]:
y[:,np.newaxis,:]

array([[[ 0,  1,  2,  3,  4,  5,  6]],

       [[ 7,  8,  9, 10, 11, 12, 13]],

       [[14, 15, 16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25, 26, 27]],

       [[28, 29, 30, 31, 32, 33, 34]]])

In [80]:
y[:,np.newaxis,:].shape # no new elements, just an increase in dimensionality

(5, 1, 7)

In [81]:
x = np.arange(5)
x[:,np.newaxis] + x[np.newaxis,:]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

The ellipsis syntax maybe used to indicate selecting in full any remaining unspecified dimensions. For example:

In [82]:
z = np.arange(81).reshape(3,3,3,3)
z[1,...,2]

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

In [83]:
z[1,:,:,2] # equivalent to the above

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

# Broadcasting

See also: the [broadcasting documentation](https://docs.scipy.org/doc/numpy-dev/user/basics.broadcasting.html) and [Array Broadcasting in numpy](http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc) from scipy.github.io.

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations.

NumPy operations are usually done on pairs of arrays on an element-by-element basis. In the simplest case, the two arrays must have exactly the same shape, as in the following example:

In [84]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([ 2.,  4.,  6.])

NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. The simplest broadcasting example occurs when an array and a scalar value are combined in an operation:

In [85]:
b = 2.0
a * b # We can think of the scalar b being stretched during the arithmetic 
      # operation into an array with the same shape as a

array([ 2.,  4.,  6.])

## The broadcasting rule

When operating on two arrays, NumPy compares their shapes element-wise.  

**Two arrays are compatible for broadcasting IFF _for each trailing dimension_**:
1. they are equal, or
2. one of them is 1.

![broadcast1.PNG](imgs/broadcast1.PNG)

![broadcast2.PNG](imgs/broadcast2.PNG)

![broadcast3.PNG](imgs/broadcast3.PNG)

Some examples:

In [86]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))

In [87]:
x

array([0, 1, 2, 3])

In [88]:
xx

array([[0],
       [1],
       [2],
       [3]])

In [89]:
y

array([ 1.,  1.,  1.,  1.,  1.])

In [90]:
z

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [91]:
x.shape, y.shape

((4,), (5,))

In [92]:
x + y # will cause shape mismatch

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [93]:
xx.shape, y.shape

((4, 1), (5,))

In [94]:
(xx + y).shape

(4, 5)

In [95]:
xx + y

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.]])

In [96]:
x + z

array([[ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.]])

## `np.broadcast`

An example using [`np.broadcast`](https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.broadcast.html): Rounding elements in an array to the number of the same index in another array, elementwise:

In [97]:
target = np.random.randn(2, 2)
roundto = np.arange(1, 5, dtype=np.int16).reshape((2, 2)) # must be type int

b = np.broadcast(target, roundto)
out = np.empty(b.shape)
out.flat = [round(u,v) for (u,v) in b]
print(out)

[[ 0.4     1.41  ]
 [-1.347   0.6262]]


# Logic functions

A few useful logic functions are highlighted below.

Source: https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.logic.html.  

In [98]:
# Truth value testing
# np.all: test whether all array elements along a given axis evaluate to True
# np.any: test whether any array element along a given axis evaluates to True
x = np.arange(5)
print(np.all(x==4), ',', np.any(x==4))

False , True


In [99]:
# Element-wise comparison (rather than comparing the two arrays as single objects)
y = x[::-1]; y # in version 1.12+, use np.flip

array([4, 3, 2, 1, 0])

In [100]:
print(np.greater(x, y))
print(np.greater_equal(x, y))
print(np.not_equal(x, y))

[False False False  True  True]
[False False  True  True  True]
[ True  True False  True  True]


# Vectorization

## `numpy.vectorize`

Docs: https://docs.scipy.org/doc/numpy/reference/generated/numpy.vectorize.html

"The vectorize function is **provided primarily for convenience, not for performance**. The implementation is essentially a `for` loop.

In [101]:
def myfunc(a, b):
    """Return a-b if a>b, otherwise return a+b"""
    if a > b:
        return a - b
    else:
        return a + b
    
# will throw error: np.array([1, 2, 3]) > 3 would return [False, False, false] 
myfunc(np.array([1, 2, 3, 4]), 2)    

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [102]:
vfunc = np.vectorize(myfunc)
vfunc([1, 2, 3, 4], 2)

array([3, 4, 1, 2])

The docstring is taken from the input function to vectorize unless it is specified:

In [103]:
vfunc.__doc__

'Return a-b if a>b, otherwise return a+b'